%% bwapi environment
active_tile_array() -> 
mini_tile_flags() -> 
tile_set_map() -> 
map_tile_array() -> 
trigger_vectors() -> 
save_game_file() -> 
current_map_file() -> 
screen_x() -> 
screen_y() -> 
move_to_x() -> 
move_to_y() -> 
replay_header() -> 
net_mode() -> 
in_replay() -> 
game_type() -> 
vissible_units() ->  
hidden_units() -> 
frame_skip() -> 
latency_frames() -> 
resource_count() -> 
gather_queue_count() -> 
next_gatherer() -> 
has_nuke() -> 
hit_points() -> 
move_target() -> 
current_direction() -> 
current_speed() ->
% explicit setters
set_local_speed() -> 
set_vision() -> 
set_frame_skip() ->
% checkers
is_game_paused() ->  
is_being_gathered() -> 
is_carrying_gas() -> 
is_carrying_minerals() -> 
is_moving() -> 
is_accelerating() -> 
is_under_storm() -> 
is_starting_attack() -> 
is_attacking() -> 
is_attack_frame() -> 
is_stuck() -> 
is_completed() -> 
is_burrowed() -> 
is_cloacked() -> 
is_gathering() -> 
is_lifted() -> 
is_powered() -> 
is_interruptible() -> 
is_hallucination() -> 
is_visible() -> 
is_detected() -> 
is_being_healed() -> 
% getters
get_mouse_position() -> 
get_hit_points() -> 
get_resource_group() -> 
get_nydus_exit() -> 
get_build_unit() -> 
get_addon() -> 
get_rally_position() -> 
get_rally_unit() -> 
get_remove_timer() -> 
get_defense_matrix_points() -> 
get_defense_matrix_timer() -> 
get_spider_mine_count() -> 
get_remaining_upgrade_time() -> 
get_remaining_research_time() -> 
get_tech() -> 
get_upgrade() -> 
get_remaining_train_time() -> 
get_player() -> 
get_order() -> 
get_order_timer() -> 
get_velocity() -> 
get_angle() -> 
get_target_position() -> 
get_energy() -> 
get_ground_weapon_cooldown() -> 
get_acid_spore_count() -> 
get_ensnare_timer() -> 
get_stim_timer() -> 
get_air_weapon_cooldown() -> 
get_spell_cooldown() -> 
get_order_target() -> 
get_order_target_position() -> 
get_shields() -> 
get_type() -> 
get_transport() -> 
get_hatchery() -> 
get_kill_count() -> 
get_last_attacking_player() -> 
get_training_queue() -> 